config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jams#index'

  # Jams routes

  get 'jam/:id', to: 'jams#archive', as: :archive_jam
  resources :jams

  # Dashboard routes

  get 'dashboard', to: 'dashboards#dashboard'

  # Profile routes

  get 'my_profile', to: 'profiles#my_profile', as: :my_profile
  get 'profile/:id', to: 'profiles#public_profile', as: :profile

  # User privacy settings

  get 'close_notice', to: 'privacy_settings#close_notice', as: :close_privacy_cookie_notice
  get 'accept_privacy_cookie', to: 'privacy_settings#accept_privacy_cookie', as: :accept_privacy_cookie
  get 'deny_privacy_cookie', to: 'privacy_settings#deny_privacy_cookie', as: :deny_privacy_cookie
  get 'reset_privacy_cookie', to: 'privacy_settings#reset_privacy_cookie', as: :reset_privacy_cookie

  # User data

  post 'local_data', to: 'local_datas#local_data'

  # Search for events => Map

  post 'search', to: 'searchs#index'

  # Save user position

  post 'save_location', to: 'save_locations#save_location', as: :save_location

  # Error pages

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/models/profile.rb
class Profile < ApplicationRecord
  after_create :attach_default_profile_photo

  belongs_to :user
  has_one :address
  has_many :posts
  has_one_attached :photo
  has_one_attached :banner

  def attach_default_profile_photo
    require 'open-uri'

    image_path = 'https://extraupdate.com/wp-content/uploads/2019/02/map_img_1138084_1501023103.jpg'
    file = URI.open(image_path)
    filename = File.basename(URI.parse(image_path).path)
    photo.attach(io: file, filename: filename)

    image_path = 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80'
    file = URI.open(image_path)
    filename = File.basename(URI.parse(image_path).path)
    banner.attach(io: file, filename: filename)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def my_profile
    @profile = current_user.profile
    authorize @profile
  end

  def public_profile
    @profile = Profile.find(params[:id])
    authorize @profile
    if @profile == current_user.profile
      redirect_to my_profile_path
    end
  end
end

app/views/profiles/my_profile.html.erb
my_profile.html.erb
<%= link_to "Edit profile", edit_user_registration_path %>

<%= link_to "privacy true", accept_privacy_cookie_path, remote: true %>
<%= link_to "privacy false", deny_privacy_cookie_path, remote: true %>
<%= link_to "privacy reset", reset_privacy_cookie_path, remote: true %>

app/views/profiles/public_profile.html.erb
<div class="profile-section section">
  <%= image_tag @profile.banner %>
  <div class="banner-separator"></div>
  <div class="profile-main-box">
    <%= image_tag @profile.photo %>
    <%= @profile.user.full_name %>
    <%= age(@profile.birth_date) %>
  </div>
  <div class="profile-spec">
    <div class="bio">
      <%= @profile.bio %>
    </div>
    <div class="profile-data">
      <%= average_rating(@profile)  %>
      <%= @profile.user.jams.where(status: "finished").count %>
      <%= @profile.user.jam_participations.count %>
      <%= @profile.user.followers.count %>
      <%= @profile.user.friends.count %>
    </div>
    <div class="profile-music">
      <%= @profile.user.instruments %>
      <%= @profile.user.music_styles %>
    </div>
  </div>
</div>
<div class="posts-section section">

</div>