config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jams#index'

  # Jams routes

  get 'jam/:id', to: 'jams#archive', as: :archive_jam
  resources :jams

  # Dashboard routes

  get 'dashboard', to: 'dashboards#dashboard'

  # Profile routes

  get 'my_profile', to: 'profiles#my_profile', as: :my_profile
  get 'profile/:id', to: 'profiles#public_profile', as: :profile

  # User privacy settings

  get 'close_notice', to: 'privacy_settings#close_notice', as: :close_privacy_cookie_notice
  get 'accept_privacy_cookie', to: 'privacy_settings#accept_privacy_cookie', as: :accept_privacy_cookie
  get 'deny_privacy_cookie', to: 'privacy_settings#deny_privacy_cookie', as: :deny_privacy_cookie
  get 'reset_privacy_cookie', to: 'privacy_settings#reset_privacy_cookie', as: :reset_privacy_cookie

  # User data

  post 'local_data', to: 'local_datas#local_data'

  # Search for events => Map

  post 'search', to: 'searchs#index'

  # Save user position

  post 'save_location', to: 'save_locations#save_location', as: :save_location

  # Error pages

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/controllers/privacy_settings_controller.rb
class PrivacySettingsController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!

  def accept_privacy_cookie
    @user_privacy_policy = cookies.permanent[:user_privacy_policy] = "true"
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'remove_notice' }
    end
  end

  def close_notice
    @user_privacy_policy = cookies[:user_privacy_policy] = "closed"
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'remove_notice' }
    end
  end

  def deny_privacy_cookie
    Address.destroy(current_user.profile.address.id) if user_signed_in? && current_user.profile.address
    @user_privacy_policy = cookies.permanent[:user_privacy_policy] = "false"
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'remove_notice' }
    end
  end

  def reset_privacy_cookie
    # Delete cookie user_privacy_policy a.k.a set it to false
    cookies.delete :user_privacy_policy
    Address.destroy(current_user.profile.address.id) if user_signed_in? && current_user.profile.address
    @user_privacy_policy = "undefined"
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'add_notice' }
    end
  end
end

app/views/privacy_settings/_notice.html.erb
<% unless @user_privacy_policy == 'true' || @user_privacy_policy == 'false' || @user_privacy_policy == 'closed' %>
  <div id="notice">
    <p>MuWe uses cookies to deliver and improve the website experience. See our <a href="#">cookie policy</a> for further details on how we use cookies and how to change your cookie settings.</p>
    <%= link_to "Accept", accept_privacy_cookie_path, remote: true %>
    <%= link_to "Close", close_privacy_cookie_notice_path, remote: true %>
  </div>
<% end %>

app/views/privacy_settings/accept_privacy_cookie.js.erb
function removeNotice() {
  const notice = document.getElementById("notice");
  if(notice) {
    notice.remove();
  }
}

removeNotice();

app/views/privacy_settings/add_notice.js.erb
function animateNotice(notice) {

}

function addNotice(new_notice)  {
  const notice = document.getElementById("notice");
  if(!notice) {
    const body = document.getElementsByTagName("body")[0];
    body.insertAdjacentHTML('afterbegin', new_notice);
    const notice = document.getElementById("notice");
    animateNotice(notice);
  }
}

addNotice('<%= j render "privacy_settings/notice" %>');

app/views/privacy_settings/remove_notice.js.erb
function removeNotice() {
  const notice = document.getElementById("notice");
  if(notice) {
    notice.remove();
  }
}

removeNotice();

app/views/privacy_settings/reset_privacy_cookie.js.erb
function addNotice(new_notice)  {
  const notice = document.getElementById("notice");
  if(!notice) {
    const header = document.getElementsByTagName("header")[0];
    header.insertAdjacentHTML('beforeend', new_notice);
  }
}

addNotice('<%= j render "privacy_settings/notice" %>');