config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jams#index'

  # Jams routes

  get 'jam/:id', to: 'jams#archive', as: :archive_jam
  resources :jams

  # Dashboard routes

  get 'dashboard', to: 'dashboards#dashboard'

  # Profile routes

  get 'my_profile', to: 'profiles#my_profile', as: :my_profile
  get 'profile/:id', to: 'profiles#public_profile', as: :profile

  # User privacy settings

  get 'close_notice', to: 'privacy_settings#close_notice', as: :close_privacy_cookie_notice
  get 'accept_privacy_cookie', to: 'privacy_settings#accept_privacy_cookie', as: :accept_privacy_cookie
  get 'deny_privacy_cookie', to: 'privacy_settings#deny_privacy_cookie', as: :deny_privacy_cookie
  get 'reset_privacy_cookie', to: 'privacy_settings#reset_privacy_cookie', as: :reset_privacy_cookie

  # User data

  post 'local_data', to: 'local_datas#local_data'

  # Search for events => Map

  post 'search', to: 'searchs#index'

  # Save user position

  post 'save_location', to: 'save_locations#save_location', as: :save_location

  # Error pages

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-upper">
    <div class="about-us">
      <h3>About us</h3>
      <p>We want to unite musicians around the world, simplify and promote musical interactions.</p>
    </div>
    <div class="footer-logo">
      <%= image_tag 'muwe-logo.svg', height: '50px', width: '50px' %>
    </div>
    <div class="contact-us">
      <h3>Contact us</h3>
      <p>Phone: ...</p>
      <p>Email: ...</p>
    </div>
  </div>
  <div class="footer-lower">
    <p>Made with <i class="fas fa-heart"></i> by MuWe</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <div class="nav-section">
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag "muwe-logo.svg", height: "65px", width: "65px" %>
        <% end %>
      </div>
    </div>

    <%= link_to new_jam_path do %>
      <div class="organise-jam-button">Organise a Jam</div>
    <% end %>

    <div class="nav-section">
      <% if user_signed_in? %>
        <div class="dashboard"><%= link_to "dashboard", dashboard_path %></div>
        <div class="profile"><%= link_to "Profile", my_profile_path %></div>
        <div class="sign-out"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></div>
        <%= link_to my_profile_path do %>
          <%= image_tag current_user.profile.photo, height: "60px", width: "60px", secure: true, class: "nav-profile-photo" %>
        <% end %>
      <% else %>
        <div class="sign-in"><%= link_to "Sign in", new_user_session_path %></div>
        <div class="sign-up"><%= link_to "Sign up", new_user_registration_path %></div>
      <% end %>
    </div>
  </nav>
</header>