config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jams#index'

  # Jams routes

  get 'jam/:id', to: 'jams#archive', as: :archive_jam
  resources :jams

  # Dashboard routes

  get 'dashboard', to: 'dashboards#dashboard'

  # Profile routes

  get 'my_profile', to: 'profiles#my_profile', as: :my_profile
  get 'profile/:id', to: 'profiles#public_profile', as: :profile

  # User privacy settings

  get 'close_notice', to: 'privacy_settings#close_notice', as: :close_privacy_cookie_notice
  get 'accept_privacy_cookie', to: 'privacy_settings#accept_privacy_cookie', as: :accept_privacy_cookie
  get 'deny_privacy_cookie', to: 'privacy_settings#deny_privacy_cookie', as: :deny_privacy_cookie
  get 'reset_privacy_cookie', to: 'privacy_settings#reset_privacy_cookie', as: :reset_privacy_cookie

  # User data

  post 'local_data', to: 'local_datas#local_data'

  # Search for events => Map

  post 'search', to: 'searchs#index'

  # Save user position

  post 'save_location', to: 'save_locations#save_location', as: :save_location

  # Error pages

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/models/jam.rb
class Jam < ApplicationRecord
  after_create :add_default_participant, :attach_default_jam_photo

  belongs_to :user
  has_one :address
  belongs_to :music_style, optional: true
  has_many :participants, dependent: :destroy
  has_one :chat
  has_one_attached :photo

  validates :max_participants, :status, :start_date, :start_time, :duration, :end_time, :music_style, presence: true

  enum status: { planned: 0, ongoing: 1, finished: 2 }

  scope :filter_by_periode_uniq, ->(periode) { where('start_date = ?', periode) }
  scope :filter_by_periode_multiple, ->(periodes) { where('start_date BETWEEN ? AND ?', periodes[0], periodes[1]) }
  scope :filter_by_time, ->(time_periode) { where('start_time >= ? AND end_time <= ?', time_periode[0], time_periode[1]) }
  scope :filter_by_start_time, ->(start_time) {  where('start_time >= ?', start_time)}
  scope :filter_by_end_time, ->(end_time) {  where('end_time <= ?', end_time)}
  scope :filter_by_max_participants, ->(max_participants) { where('max_participants <= ?', max_participants) }
  scope :filter_by_status, ->(status) { where(status: status) }
  scope :filter_by_duo_status, ->(status_multiple) { where(status: status_multiple) }

  def add_default_participant
    participants.create!(user: user, status: 1)
  end

  def attach_default_jam_photo
    require 'open-uri'

    image_path = 'https://res.cloudinary.com/dis87nwse/image/upload/v1586260281/image_not_found.svg'
    file = URI.open(image_path)
    filename = File.basename(URI.parse(image_path).path)
    photo.attach(io: file, filename: filename) unless self.photo.attachment
  end

  def count_participants
    participants.count
  end
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController

  def index
    @jams = policy_scope(Jam)
    authorize @jams
  end

  def new
    @jam = Jam.new
    authorize @jam
  end

  def create
    @jam = Jam.new(jam_params)
    @jam.end_time = @jam.start_time + @jam.duration
    @jam.user = current_user
    set_address
    @jam.address = @address
    authorize @jam
    if @jam.save
      redirect_to jam_path(@jam.id)
    else
      render :new
    end
  end

  def show
    set_jam
  end

  def edit
    set_jam
  end

  def update
    set_jam
    if @jam.update(jam_params)
      redirect_to @jam
    else
      render :edit
    end
  end

  def archive
    set_jam
    @jam.finished!
    if @jam.save
      redirect_to root_path
    else
      redirect_to jam_path(@jam.id)
    end
  end

  def destroy
    set_jam
    @jam.destroy!
    redirect_to root_path
  end

  private

  def jam_params
    params.require(:jam).permit(
      :user_id,
      :music_style_id,
      :description,
      :max_participants,
      :status,
      :start_date,
      :start_time,
      :duration,
      :privacy,
      :photo
    )
  end

  def set_jam
    @jam = Jam.find(params[:id])
    authorize @jam
  end

  def set_address
    if params[:jam][:other][:given_address]
      given_address = params[:jam][:other][:given_address]
      if given_address =~ /^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?)\s[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/
        coords = given_address.split(/\s/)
        address = Geocoder.search(coords).first
        @address = Address.new(given_address: given_address, street: address.street, postal_code: address.postal_code, city: address.city, country: address.country, latitude: address.latitude.round(7), longitude: address.longitude.round(7))
      else
        address = Geocoder.search(given_address).first
        return unless address

        @address = Address.new(given_address: given_address, street: address.street, postal_code: address.postal_code, city: address.city, country: address.country, latitude: address.latitude.round(7), longitude: address.longitude.round(7))
      end
    end
  end
end

app/views/jams/_jam.html.erb
<div class="jam-card swiper-slide">
  <div class="jam-card-left">
    <div class="jam-image">
      <%= image_tag jam.photo, width: "130px", height: "175px", secure: true %>
      <div class="jam-status">
        <% if jam.ongoing? %>
          <i class="fas fa-circle" style="color: #36B554"></i> <!-- Green -->
          <p style="color: #36B554"><%= jam.status.capitalize %></p>
        <% elsif jam.planned? %>
          <i class="fas fa-circle" style="color: #42ABE7"></i> <!-- Blue -->
          <p style="color: #42ABE7"><%= jam.status.capitalize %></p>
        <% else %>
          <i class="fas fa-circle" style="color: #7B7B7B"></i> <!-- Gray -->
          <p style="color: #7B7B7B"><%= jam.status.capitalize %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="jam-card-right">
    <div class="jam-address">
      <p><%= jam.address.street %>, <%= jam.address.city %>, <%= jam.address.country %></p>
    </div>
    <div class="jam-time">
      <p>From </p><p class="muwe-text"><%= jam.start_time.strftime("%H:%M") %></p><p> until </p><p class="muwe-text"><%= jam.end_time.strftime("%H:%M") %></p>
    </div>
    <div class="jam-host">
      <p>Host : </p><p class=""><%= link_to profile_path(jam.user.id) do %><%= jam.user.first_name %><% end %></p>
    </div>
    <div class="jam-participants">
      <p>Participants : </p><p class="muwe-text"><%= jam.participants.count %>/<%= jam.max_participants %></p>
    </div>
  </div>
</div>

app/views/jams/_jam_form.html.erb
<%= simple_form_for @jam do |f| %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.association :music_style, label_method: :music_style %>
  <%= f.input :max_participants, collection: 2..16 %>
  <%= f.input :start_date %>
  <%= f.input :start_time, collection: time_array %>
  <%= f.input :duration, collection: time_array %>
  <%= f.input :privacy %>
  <%= f.fields_for :other do |o| %>
    <%= o.input :given_address %>
  <% end %>
  <%= f.submit %>
<% end %>

<img src="" id="photo_output">
<div class="small-map" id="map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<%= javascript_pack_tag 'image_previewer' %>
<%= javascript_pack_tag 'address_selector' %>

app/views/jams/edit.html.erb
<%= render 'jam_form', jam: @jam %>

app/views/jams/index.html.erb
<div class="map-section">

  <div class="filter-wrapper wrapper">
    <div id="proximity-data">You and <p>?</p> other signed-in Users are around <p>?</p>.</div>
    <%= render 'searchs/filter_form' %>
  </div>

  <div id="jams" class="jam-wrapper wrapper">
    <%= image_tag "arrow.svg", class: "jam-swiper-button-prev jams-next" %>
    <div class="jam-swiper-container">
      <div class="swiper-wrapper"></div>
    </div>
    <%= image_tag "arrow.svg", class: "jam-swiper-button-next jams-previous" %>
  </div>

  <div class="map-wrapper">
    <div class="big-map" id="map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

</div>

<div class="posts-section">
  <div id="local-posts" class="local-post-wrapper wrapper">
    <%= image_tag "arrow.svg", class: "local-post-swiper-button-prev local-posts-next" %>
    <div class="local-post-swiper-container">
      <div class="swiper-wrapper"></div>
    </div>
    <%= image_tag "arrow.svg", class: "local-post-swiper-button-next local-posts-previous" %>
  </div>
</div>

<%= javascript_pack_tag 'init_mapbox' %>
<%= javascript_pack_tag 'swiper' %>

app/views/jams/new.html.erb
<%= render 'jam_form', event: @event %>

app/views/jams/show.html.erb
<%= @jam.user.full_name %>
<%= image_tag @jam.photo, height: "100px", width: "100px" %>
<%= @jam.description %>

<%= link_to "Edit", edit_jam_path(@jam.id) %>
<%= link_to "Archive", archive_jam_path(@jam.id) %>
<%= link_to "Delete", jam_path(@jam.id), method: "delete" %>